OnlineStore/urls.py

from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls')),
    
]

store/urls.py
from django.contrib import admin
from django.urls import path
from .import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    
    path('',views.home,name='home'),
    path('signup/',views.sign_up,name='signup'),
    path('signin/',views.sign_in,name='signin'),
    path('logout/',views.user_logout,name='logout'),
    
    path('cart/',views.cart,name='cart'),
    
    path('dashboard/',views.dashboard,name='dashboard'),
    path('contact/',views.contact,name='contact'),
    path('additem/',views.additem,name='additem'),
    path('updateitem/<int:id>/',views.updateitem,name='updateitem'),
    path('delitem/<int:id>/',views.delitem,name='delitem'),
    
    path('ConfirmOrder/',views.ConfirmOrder,name='ConfirmOrder'),
    
    path('soled/',views.soleditems,name='soled'),
    
    path('addtobuy/<int:id>/',views.addtobuy,name='addtobuy'),
    
    path('about/',views.about,name='about'),
    path('userrequest/',views.userrequest,name='userrequest'),
    
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

store/models.py
from django.db import models

# Create your models here.
import datetime
import os

class Usersignup(models.Model):
    name = models.CharField(max_length=80)
    contactnum = models.CharField(max_length=12)
    postadress = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    password = models.CharField(max_length=32)
    

class user_contact(models.Model):
    name=models.CharField(max_length=100)
    email=models.EmailField(max_length=100)
    phone=models.CharField(max_length=70)
    massage=models.TextField(max_length=500)
    
def filepath(request, filename):
    old_filename = filename
    timeNow = datetime.datetime.now().strftime('%Y%m%d%H:%M:%S')
    filename = "%s%s" % (timeNow, old_filename)
    return os.path.join('store/static/img', filename)
    
    
class Product(models.Model):
    product_id=models.AutoField
    product_name=models.CharField(max_length=50,null=True)
    category=models.CharField(max_length=50,default="",null=True)
    price=models.IntegerField(default=0,null=True)
    desc=models.TextField(max_length=500,null=True)
    pub_date=models.DateField(null=True)
    image=models.ImageField(upload_to=filepath,null=True, blank=True)
    
class Order(models.Model):
    name =models.CharField(max_length=70)
    cnum =models.IntegerField(max_length=14)
    pstad =models.CharField(max_length=50)
    city =models.CharField(max_length=50)
    payment =models.CharField(max_length=30)
    
def ConfirmOrderImagePath(request, filename):
    old_filename = filename
    timeNow = datetime.datetime.now().strftime('%Y%m%d%H:%M:%S')
    filename = "%s%s" % (timeNow, old_filename)
    return os.path.join('store/static/confirm', filename) 
   
        
class Cart(models.Model):
    image=models.ImageField(upload_to=ConfirmOrderImagePath,null=True, blank=True)
    product_name=models.CharField(max_length=50,null=True)
    desc=models.TextField(max_length=500,null=True)
    price=models.IntegerField(default=0,null=True)
    
def Soleditems(request, filename):
    old_filename = filename
    timeNow = datetime.datetime.now().strftime('%Y%m%d%H:%M:%S')
    filename = "%s%s" % (timeNow, old_filename)
    return os.path.join('store/static/soled', filename)     
 
class Soled_item(models.Model):
    image=models.ImageField(upload_to=Soleditems,null=True, blank=True)
    product_name=models.CharField(max_length=50,null=True)
    desc=models.TextField(max_length=500,null=True)
    price=models.IntegerField(default=0,null=True)    

store/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm #for creating user
from django.contrib.auth.forms import AuthenticationForm #for Login 
from django.contrib.auth.forms import UsernameField #for Login 
from django.utils.translation import gettext,gettext_lazy as _
from .models import Product

#SignUp UserCreationForm Custom form 
class SignUpForm(UserCreationForm):
    password1=forms.CharField(label='Password',widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2=forms.CharField(label='Confirm Password (again)',widget=forms.PasswordInput(attrs={'class':'form-control'}))
    class Meta:
        model=User
        fields=['username','first_name','last_name','email']
        labels= {'first_name':'First Name','last_name':'Last Name','email':'Email',}
        
        widgets={'username':forms.TextInput(attrs={'class':'form-control',}),
                'first_name':forms.TextInput(attrs={'class':'form-control'}),
                'last_name':forms.TextInput(attrs={'class':'form-control'}),
                'email':forms.TextInput(attrs={'class':'form-control'})
        }
        
       
class SignInForm(AuthenticationForm):
    username=UsernameField(widget=forms.TextInput(attrs={'autofocus':True, 'class':'form-control'}))
    password=UsernameField(label=_("Password"),strip=False,widget=forms.PasswordInput(attrs={'autofocus':True, 'class':'form-control'})) 
    
# class add_item(forms.ModelForm):
#     class Meta:
#         model = Product 
#         fields=['product_name','category','price','desc','pub_date','image']  
#         labels={'product_name':'Product Name','category':'Category','price':'Price','desc':'Description','pub_date':'Publish Date','image':'Image'}
       
#         widgets={'product_name':forms.CharField(),
#                  'category':forms.CharField(),
#                  'price':forms.IntegerField(),
#                  'desc':forms.Textarea(),
#                  'pub_date':forms.DateField(),
#                  'image':forms.ImageField(),
#                 }                

store/views.py
from django.shortcuts import render,HttpResponseRedirect
from django.contrib import messages
from .forms import SignUpForm,SignInForm
from django.contrib.auth.forms import AuthenticationForm
# from .forms import SignUpForm,SignInForm,PostForm
from django.contrib.auth import authenticate,login,logout #for login
from .models import Usersignup,user_contact,Product,Order,Cart,Soled_item
# Create your views here.
import os
from django.contrib.auth.models import Group
from django.core.paginator import Paginator
def home(request):
    products=Product.objects.all()
    
    return render(request,'store/home.html',{'products':products,'name':request.user.username})

def additem(request):
    if request.user.is_authenticated:
        if request.method=='POST': 
            pro=Product()
            pro.product_name=request.POST.get('product_name')
            pro.category=request.POST.get('category')
            pro.price=request.POST.get('price')
            pro.desc=request.POST.get('desc')
            pro.pub_date=request.POST.get('pub_date')
            
            if len(request.FILES)!=0:
                pro.image=request.FILES['image']

            # pst=Product(product_name=product_name,category=category,price=price,desc=desc,pub_date=pub_date,image=img)
            pro.save()
            messages.success(request, 'Item Added Sueccssfuly!')
            return render(request,'store/additem.html')
                
        else:
            return render(request,'store/additem.html')
    else:
        return HttpResponseRedirect('/signin/')

def updateitem(request,id):
    if request.user.is_authenticated:
        itm=Product.objects.get(id=id)
        if request.method=='POST':
            if len(request.FILES)!=0:
                if len(itm.image)>0:
                    os.remove(itm.image.path)
                itm.image=request.FILES['image']
            itm.product_name=request.POST.get('product_name')
            itm.category=request.POST.get('category')
            itm.price=request.POST.get('price')
            itm.desc=request.POST.get('desc')
            itm.pub_date=request.POST.get('pub_date')
            itm.save()
            messages.success(request, 'Updated Sueccssfuly!')
            return HttpResponseRedirect('/dashboard/')
  
        return render(request,'store/updateitem.html',{'items':itm})
    else:
        return HttpResponseRedirect('/signin/')
def delitem(request,id):
    if request.user.is_authenticated:
        itm=Product.objects.get(id=id)
        itm.delete()
        messages.success(request, 'Deleted Sueccssfuly!')
        return HttpResponseRedirect('/dashboard/')
    else:
        return HttpResponseRedirect('/signin/')       
    
 
def about(request):
    return render(request,'store/about.html') 
 
def userrequest(request):
    req=Usersignup.objects.all()
    return render(request,'store/userrequest.html',{'reqts':req}) 



# SignUp using django UserCreationForm
def sign_up(request):
    if request.method=='POST':
        fm=SignUpForm(request.POST)
        if fm.is_valid():
            user=fm.save()
            group=Group.objects.get(name='User')
            user.groups.add(group)
            messages.info(request,'Signup Successfully!')
            fm=Product.objects.all()
            return render(request,'store/home.html',{'products':fm,'name':request.user.username})  
     
    else:
        fm=SignUpForm()
    return render(request,'store/signup.html',{'form':fm})
    
    
def sign_in(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            fm = SignInForm(request=request,data=request.POST)
            if fm.is_valid():
                uname=fm.cleaned_data['username']
                upass=fm.cleaned_data['password']
                print(uname)
                user=authenticate(username=uname,password=upass)
                if user is not None:
                    
                    login(request,user)
                    messages.success(request, 'Logged in Sueccssfuly!')
                    fm=Product.objects.all()
                    return render(request,'store/home.html',{'products':fm,'name':request.user.username})  
        else:
            fm= SignInForm()
        return render(request,'store/signin.html',{'form':fm})
    else:
        return HttpResponseRedirect('/products/')
 
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/')
     

def cart(request):
    ck=Cart.objects.all()
    total=0
    for c in ck:
        total=total+c.price
    print(total)    
   
    return render(request,'store/order.html',{'products':ck,'tprice':total})  


def dashboard(request):
    if request.user.is_authenticated:
        order=len(Order.objects.all())
    
        if request.user.is_superuser == True:
            products=Product.objects.all().order_by('id')
            paginator=Paginator(products,3,orphans=1)
            page_number= request.GET.get('page')
            product_page = paginator.get_page(page_number)
            
            return render(request,'store/dashboard.html',{'products':product_page,'total':order})
           
        else:
            return HttpResponseRedirect('/')
    else:
        return HttpResponseRedirect('/signin/')


#contect model data saveing function
def addtobuy(request,id):
    if request.user.is_authenticated:
        itm=Product.objects.get(id=id)
        tobuy=Cart(image=itm.image,product_name=itm.product_name,desc=itm.desc,price=itm.price)
        tobuy.save()
        return HttpResponseRedirect('/') 
        
        
    else:
        messages.success(request, 'Please Login first!')
        return HttpResponseRedirect('/signin/')    
    


def ConfirmOrder(request):
    if request.method =='POST':
        name=request.POST.get('name')
        cnum=request.POST.get('cnum')
        pstad=request.POST.get('pstad')
        city=request.POST.get('city')
        payment=request.POST.get('payment')
        cn=Order(name=name,cnum=cnum,pstad=pstad,city=city,payment=payment)
        cn.save()
        cart=Cart.objects.all()
        
        for c in cart:
            soled=Soled_item(image=c.image,product_name=c.product_name,desc=c.desc,price=c.price)
            soled.save()
        Cart.objects.all().delete()
        
        messages.success(request, 'Oredr Conformed Shoping more!')
        return HttpResponseRedirect('/') 
    
 
def soleditems(request):
    soled=Soled_item.objects.all()
    byr=Order.objects.all() 
    return render(request,'store/soled.html',{'products':soled,'buyers':byr})    
    


def contact(request):
    if request.method =='POST':
        name=request.POST.get('name')
        email=request.POST.get('email')
        phone=request.POST.get('phone')
        massage=request.POST.get('desc')
        cn=user_contact(name=name,email=email,phone=phone,massage=massage)
        cn.save()
        messages.success(request, 'Massage Sent!')
        return render(request,'store/contact.html') 
    return render(request,'store/contact.html')       

store/templates/store/about.html
{% extends 'store/base.html' %} 

{% block body %}

<div class="container">
    <h1>About page</h1><br>
    <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit.
        Culpa ex iste dolor pariatur natus, 
        molestiae nihil aliquid, quae illo aspernatur alias quidem
        sint reprehenderit omnis! Necessitatibus aperiam perferendis facilis similique?
    </p><br><br>
    <p>
    Lorem, ipsum dolor sit amet consectetur adipisicing elit. 
    Pariatur aspernatur ipsum nostrum numquam
    facilis sapiente, impedit voluptates minus ut, consequatur tempora 
    mollitia excepturi dolore dicta eaque, doloremque non itaque provident!
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores repellendus, 
    ratione vero nam maxime esse corporis amet incidunt fuga voluptas voluptates
    odio nostrum nihil obcaecati nesciunt quam quos, excepturi eveniet.
    </p>
</div>

{%endblock body %}

store/templates/store/additem.html
{% extends 'store/base.html' %}
{% block title %} Add item {% endblock title %}

{% block body %} 

<div class="container">
    <div class="col-sm-10" >
        <h1 align="center" class="my-5">Dasheboard/Add Post</h1>

            <!-- Using Messages django -->
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                <strong>{{message}}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endfor %}
            {% endif %}


        <form action="" method="POST" enctype="multipart/form-data" novalidate>
            {% csrf_token %}
            <div class="form-group">
                <label for="">Product Name:</label>
                <input type="text" class="form-control" id="product_name" name="product_name"  placeholder="Product Name">
            </div>

              <div class="form-group">
                <label for="">Category:</label>
                <input type="text" class="form-control" id="category" name="category" placeholder="Category">
              </div>
            
              <div class="form-group">
                <label for="">Price:</label>
                <input type="number" class="form-control" id="price" name="price" placeholder="Product Price">
            </div>

            <div class="form-group">
                <label for="">Description:</label>
                <textarea class="form-control" id="desc" rows="3" name="desc" placeholder="Desc"></textarea>
            </div>

            <div class="form-group">
                <label for="">Publish Date:</label>
                <input type="date" class="form-control" id="pub_date" name="pub_date"  placeholder="Publish Date">
            </div>

            <div class="form-group">
                <label for="">Product Image</label>
                <input type="file" class="form-control" id="image" name="image">
            </div>

            <input type="submit" value="Add" class="btn btn-success" >
            <a href="{% url 'dashboard' %}" class="btn btn-danger"> Cancel</a>
            
        </form>

    </div>
</div> 

{% endblock body %} 

store/templates/store/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>{% block title %}{% endblock title %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Online Makeup Store</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            {% if request.user.is_authenticated %}
            <a class="nav-item nav-link active" href="/">Home <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="#">Categarys</a>
            <a class="nav-item nav-link" href="{% url 'about' %}">About</a>
            <a class="nav-item nav-link" href="{% url 'contact'%}">Contact</a>
            <a class="nav-item nav-link" href="{% url 'logout'%}">Logout</a>
            {% if perms.store %}
            <a class="nav-item nav-link" href="{% url 'dashboard'%}">Dashboard</a>
            {% endif %}
            {% else %}
            <a class="nav-item nav-link active" href="/">Home <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="#">Categarys</a>
            <a class="nav-item nav-link" href="{% url 'about' %}">About</a>
            <a class="nav-item nav-link" href="{% url 'contact'%}">Contact</a>
            <a class="nav-item nav-link" href="{% url 'signup'%}">Singup</a>
            <a class="nav-item nav-link" href="{% url 'signin'%}">Singin</a>
            
            
            {% endif %}
          </div>
        </div>
      </nav>
    
    
    
      {% block body %}{% endblock body %}
    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

store/templates/store/contact.html
{% extends 'store/base.html' %} 

{% block body %}
  <div class="container">

  <h1 align="center">Contact Us</h1>

      <!-- Using Messages django -->
      {% if messages %}
      {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        <strong>{{message}}</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button> 
      </div>
      {% endfor %}
      {% endif %}
  
  <form  method="POST" action="/contact/" >
    {% csrf_token %}

    <div class="mb-3">
        <label for="name" class="form-label">Name:</label>
        <input type="text" class="form-control" id="name" name="name" required placeholder="Please enter you'r name">
    </div>

    <div class="mb-3">
      <label for="email" class="form-label">Email:</label>
      <input type="email" class="form-control" id="email" name="email" required placeholder="Please enter you'r Email">
      <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
    </div><br>

    <div class="mb-3">
      <label for="phone" class="form-label">Phone Number:</label>
      <input type="phone" class="form-control " id="phone" name="phone" required placeholder="Please enter you'r phone number">
    </div>

    <div class="form-floating" >
      <label for="desc" class="form-label">Comment:</label>   
      <textarea class="form-control" placeholder="Leave a massage here" id="desc" required name="desc" style="height: 100px"></textarea>
    </div><br>
    
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

  </div>
{% endblock body%}

store/templates/store/dashboard.html
{% extends 'store/base.html' %}

{% block body%}
{% load static %}<br><br>

<div class="container">
    <!-- Using Messages django -->
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        <strong>{{message}}</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
    {% endif %}

    


<div class="container" >
    <h1 align="center" class="my-5">Dasheboard</h1>
    <div>
    
    <a href="{% url 'additem' %}" class="btn btn-success"> Add Item</a>
    <a  href="{% url 'soled' %}" class="btn btn-primary">
      Orders details <span class="badge badge-light">{{total}}</span>
    </a><br>
    

  <br>
  <div class="row">
    <div class="col-sm-12">
      <h4 class="text-center alert alert-primary" align="center">Avalible Products</h4>
      {% if products %}
      <table class="table table-hover">
          <thead>
            <tr>
              <th scope="col">Item ID</th>
              <th scope="col" style="width: 10%;">Image</th>
              <th scope="col" >Product Name</th>
              <th scope="col" style="width: 30%;">Desc</th>
              <th scope="col">Category</th>
              <th scope="col">Publish Date</th>
              <th scope="col" >Price</th>
              <th scope="col" >Action</th>
            </tr>
          </thead>
          <tbody>
              {% for produ in products %}
            <tr>
              <th scope="row">{{produ.id}}</th>
              {% if produ.image %}
                <td>
                  <img src="{{ produ.image.url }}" alt="" class="img-thumbnail ">
                </td>
              {% else %} 
                <td>
                  image
                </td>
              {% endif %}   
              
              <td>{{produ.product_name}}</td>
              <td>{{produ.desc}}</td>
              <td>{{produ.category}}</td>
              <td>{{produ.pub_date}}</td>
              <td>{{produ.price}}</td>
              <td><a class="btn btn-primary btn-sm" href="{% url 'updateitem' produ.id %}">Edit</a><br>

                  <a class="btn btn-danger btn-sm" href="{% url 'delitem'  produ.id %}" >Delete</a>
              </td>
            </tr>
            {% endfor %}
          
          </tbody>
        
        </table>
        {% else %}
        <h4 class="text-cebter alert alert-info mt-3" align="center">Products Not Avalible </h4>
      {%endif %}
      <div>
       
       

        <nav aria-label="Page navigation example">
          <ul class="pagination justify-content-center">
            {% if products.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{products.previous_page_number}}">Previous</a></li>
            {% else %}
            <li class="page-item disabled">
              <a class="page-link" href="#" tabindex="-1">Previous</a>
            </li
            {% endif %}

            <li class="page-item"><span  class="page-link">Page {{products.number}} of {{ products.paginator.num_pages}}</span></li>
            
            {% if products.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{products.next_page_number}}">Next</a></li>
            {% endif %}
        </span>
      </ul>
    </nav> 

    </div>
    </div>  
  </div>    
</div> 

</div>

{% endblock body %}

store/templates/store/home.html
{% extends 'store/base.html' %}

{% block title %} Home {% endblock title %}

{% block body %}
{% load static %}

<script src="{% static 'js/script.js' %}"></script>
<br><br>
<div class="col-sm-8 mx-auto">
    <h1 align="center">Home Page</h1>
    <a class="btn btn-danger btn-lg"  href="{% url 'cart' %}" role="button">Go to Cart</a>
        <!-- Using Messages django -->
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            <strong>{{message}}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
        {% endif %}
        
    <h1>Welcome {{name}}</h1>
    {% for prod in products %}
        <div class="jumbotron d-flex " >
            
                <div class="col-5">
                <img src="/media/{{ prod.image}}" alt="{{ prod.category }}" class="rounded img-fluid img-thumbnail">
                </div>
                <div class="col-5">
                    <h1 class="display-8">{{prod.product_name}}</h1>
                    <p class="lead">Desc. {{prod.desc}}</p>
                    <hr class="my-8">
                    <h3>Rs.{{prod.price}}</h3><br>
                    {% comment %} {% if perms.store.view_product %}
                    <a class="btn btn-danger btn-lg" onclick="myFunction()" href="{% url 'addtobuy'  prod.id %}" role="button">Add to Chart</a>
                    {% else %} 
                    <a class="btn btn-danger btn-lg"  href="{% url 'addtobuy'  prod.id %}" role="button">Add to Cart</a>
                    {% endif %} {% endcomment %}
                    <a class="btn btn-danger btn-lg" onclick="myFunction()" href="{% url 'addtobuy'  prod.id %}" role="button">Add to cart</a>
                </div>
                <br>   
            
        </div>
    {% endfor %}
    

</div>
{% endblock body %}

store/templates/store/order.html
{% extends 'store/base.html' %} 

{% block body %}
<br>
<div class="container">
   

   <h2 class="text-center alert alert-danger">Order Confirmation Form</h2>
      <div class="row">
         <div class="col-sm-6">
            <h2 class="text-center alert alert-primary">Products</h2>
            <table class="table table-hover">
               <thead>
                  <tr>
                     <th scope="col" style="width: 10%;">Image</th>
                     <th scope="col" >Product Name</th>
                     <th scope="col" style="width: 40%;">Desc</th>
                     <th scope="col">Price</th>
                  </tr>
               </thead>
               <tbody>
                  {% for produ in products %}
                  <tr>
                     {% if produ.image %}
                        <td><img src="{{ produ.image.url }}" alt="" class="img-thumbnail "></td>
                     {% else %} 
                        <td>image</td>
                     {% endif %}   
                     <td>{{produ.product_name}}</td>
                     <td>{{produ.desc}}</td>
                     <td><b>{{produ.price}}</td>
                     {% endfor %}  
                  </tr>
               </tbody>
            </table><br>
            <h2>Total Price Rs-/{{tprice}}</h2>
         </div> 
            
            
         
            <div class="col-sm-6">
               <h2 class="text-center alert alert-primary">Dilvery Address</h2>
               <form  method="POST" action="/ConfirmOrder/" >
                  {% csrf_token %}
            
                  <div class="mb-3">
                     <label for="name" class="form-label">Name:</label>
                     <input type="text" class="form-control" id="name" name="name" required placeholder="name">
                  </div>
            
                  <div class="mb-3">
                  <label for="email" class="form-label">Contact Number:</label>
                  <input type="tel" class="form-control" id="cnum" name="cnum" required laceholder="03055535384"> 
                  </div>
            
                  <div class="mb-3">
                  <label for="phone" class="form-label">Postal Address:</label>
                  <input type="text" class="form-control " id="pstad" name="pstad" required placeholder="Postal Address">
                  </div>

                  <div class="mb-3">
                     <label for="phone" class="form-label">City:</label>
                     <input type="text" class="form-control " id="city" name="city" required placeholder="City">
                  </div>

                  <div class="mb-3">
                     <label for="phone" class="form-label">Cash on delivery :</label>
                     <input type="text" class="form-control"  id="payment" name="payment" required placeholder="Yes or No">
                  </div>
                  
                  <button type="submit" class="btn btn-primary">Submit</button>
               </form>
            </div>   
           
      </div>      
</div>

{% endblock body %}

store/templates/store/products.html
{% extends 'store/base.html' %}
{% block title %} Signin {% endblock title %}
{% block body %} 


<div class="container">
    <h1 align="center">Avaliable Products</h1><br>
    <!-- Using Messages django -->
    {% if messages %} {% for message in messages %}
    <div
      class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
      <strong>{{message}}</strong>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %} {% endif %}

    

</div>    
{% endblock body %} 